force-app/main/default/objects/Quote/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Initial_Quote_Sent__c.field-meta.xml
<CustomField>
    <fullName>Initial_Quote_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if you have notified the client of the Initial Quote.</description>
    <inlineHelpText>Check if you have notified the client of the Initial Quote</inlineHelpText>
    <label>Initial Quote Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>TotalPrice  +  VAT_Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount (Net + VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discounted_Amount__c</fullName>
    <formula>Discount  *  Subtotal</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Discounted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT_Tax__c.field-meta.xml
<CustomField>
    <fullName>VAT_Tax__c</fullName>
    <formula>TotalPrice   * 0.20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Total_Discounted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discounted_Amount__c</fullName>
    <formula>Quote.Subtotal -  Quote.TotalPrice</formula>
    <label>Total Discounted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteModel.cls
public with sharing class QuoteModel {
    // TODO: merge this with SOQL for Quote Line items
    // in this format-ish: SELECT Id, (SELECT Id FROM QuoteLineItems) FROM Quote where Id =: quoteId
    @AuraEnabled(cacheable=true)
    public static List<Quote> getQuote(Id quoteId){

        List<Quote> qs = [
            SELECT Id, Name, LineItemCount, Subtotal, 
            Total_Discounted_Amount__c, Discount, 
            Total_Amount__c, TotalPrice, VAT_Tax__c, 
            Status, Approval_Status__c, Initial_Quote_Sent__c
            FROM Quote
            WHERE Id =:quoteId
            LIMIT 1
            ];

        // Should not be empty since a quoteId was passed to this
        if (qs.size() == 0) {
            throw new AuraHandledException('No Quote found for the provided ID.');
        }

        return qs;
    }

    @AuraEnabled(cacheable=true)
    public static List<QuoteLineItem> getQuoteLineItems(Id quoteId){
        // This can be empty if displaying dashboard for a 
        // quote without line items yet
        return [
            SELECT Id, Product2.Name, Quantity, Subtotal, Discount, TotalPrice
            FROM QuoteLineItem
            WHERE QuoteId = :quoteId
        ];
    }
}